version: '3'
services:
  cc-rest:
    container_name: cc-rest
    ports:
      - ${CC_REST_PORT}:5000
    build:
      context: ./CarbonComply-rest
    environment:
      DATA_FOLDER: '${DATA_FOLDER}'

  cc-web:
    container_name: cc-web
    build:
      context: ./carboncomply-web
      args:
        - API_URL=http://${SERVER_NAME}:${CC_REST_PORT}
    ports:
      - ${CC_UI_PORT}:80
    depends_on:
      - cc-rest
